### PR TITLE
Fix hash issues

### LINKED ISSUE #25: Too much constexpr in hashers
Currently the implementation detail of `YK_ADAPT_HASH` and many hash-related functions are defined as `constexpr`, however many existing hasher specializations are never defined as `constexpr` for historical reasons. Especially `boost::hash_combine`, `boost::hash_range`, etc. is very problematic since it suddenly starts to yield compile error when the functions can not be implicitly converted to constexpr by the compiler (I guess)

### LINKED ISSUE #27: hash related bug/regression since #26
`yk/hash/hash_combine.hpp`
- include guard is wrong
- should include `<boost/container_hash/hash.hpp>` instead of `_fwd.hpp` because `yk::hash_combine` is providing an implementation, not just a declaration

---

#25 is still active; My app fails to compile without my local patch (which removes `constexpr`) on `YK_ADAPT_HASH` family.

```
[snip]: error C3615: constexpr function 'std::hash<ygo::game::MonsterDesignation>::operator ()' cannot result in a constant expression (compiling source file src\JSONParser.cpp)
[snip]: message : failure was caused by call of undefined function or one not declared 'constexpr' (compiling source file src\JSONParser.cpp)
[snip]: message : see usage of 'boost::hash_combine' (compiling source file src\JSONParser.cpp)
```

@yaito3014 Could you take a look into this? 🥺

### PR DESCRIPTION
**Pull request by yaito3014**
fixes #25, fixes #27

### CODE REVIEW

**Review by saki7 — COMMENTED** [review]
💡**Protip:** Don't forget to add `inline` when you remove `constexpr`!

**Review by saki7 — COMMENTED** [review]
Include guard for `yk/hash/adapt.hpp` is still inconsistent; you should probably recheck all hash-related headers.

**Comment by yaito3014** [comment]
should `proxy_hash.hpp` and `string_hash.hpp` be in `yk/hash` directory?

**Comment by saki7** [comment]
> should `proxy_hash.hpp` and `string_hash.hpp` be in `yk/hash` directory?

Good catch, they should indeed be in the directory as you said.

**Review by saki7 — APPROVED** [review]
OK you can merge this anytime soon, if you have pending cosmetic changes feel free to push it too.

**Comment by saki7** [comment]
Thanks!
