### ISSUE TITLE
hash related bug/regression since #26

### ISSUE THREAD

**Issue by saki7** [yaito3014/yk_util#27]
`yk/hash/hash_combine.hpp`
- include guard is wrong
- should include `<boost/container_hash/hash.hpp>` instead of `_fwd.hpp` because `yk::hash_combine` is providing an implementation, not just a declaration

---

#25 is still active; My app fails to compile without my local patch (which removes `constexpr`) on `YK_ADAPT_HASH` family.

```
[snip]: error C3615: constexpr function 'std::hash<ygo::game::MonsterDesignation>::operator ()' cannot result in a constant expression (compiling source file src\JSONParser.cpp)
[snip]: message : failure was caused by call of undefined function or one not declared 'constexpr' (compiling source file src\JSONParser.cpp)
[snip]: message : see usage of 'boost::hash_combine' (compiling source file src\JSONParser.cpp)
```

@yaito3014 Could you take a look into this? 🥺

**Comment by saki7** [comment]
Note that the `constexpr` error is implicitly generated by MSVC. What I have in my code is just a definition which calls `yk::hash_combine` inside `YK_ADAPT_HASH`, I'm not even trying to do any hashing process during compile time.
